name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  release_job:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Check-out Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            # See: https://goreleaser.com/ci/actions/

#      - name: Install Cosign
#        uses: sigstore/cosign-installer@main
#
#      - name: Check Cosign installation
#        run: cosign version

      - name: Build Targets
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          UPLOAD_MODE: none
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
          #COSIGN_PWD: ${{ secrets.COSIGN_PWD }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Upload Binaries
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

